CREATE TABLE recipes (
    recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_title TEXT NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    recipe_prep_time TEXT,
    recipe_cook_time TEXT,
    recipe_servings INTEGER,
    recipe_ingredients TEXT,
    recipe_directions TEXT,
    recipe_folder INTEGER
        REFERENCES folders(folder_id) ON DELETE CASCADE NOT NULL,
    content TEXT
);